QandA/urls.py
from django.urls import path
from . import views

app_name= "QandA"
urlpatterns = [
    path("", views.index, name="index"),
    path("addQuestion", views.addQuestion, name="addQuestion"),
    path("addText", views.addText, name="addText")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('QandA/', include("QandA.urls"))
]

QandA/models.py
from django.db import models

# Create your models here.

QandA/views.py
from django.shortcuts import render
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect
from allennlp.predictors.predictor import Predictor
import allennlp_models.rc

predictor = Predictor.from_path(
    "https://storage.googleapis.com/allennlp-public-models/bidaf-elmo.2021-02-11.tar.gz")


class NewTextForm(forms.Form):
    text = forms.CharField(label=False, widget=forms.Textarea)


class NewQuestionFrom(forms.Form):
    question = forms.CharField(label="Question")


myquestion = ""
mytext = ""



# Create your views here.
def index(request):
    if "Text" not in request.session:
        request.session["Text"] = ""

    if "QuestionSession" not in request.session:
        request.session["QuestionSession"] = ""

    if "AnswerSession" not in request.session:
        request.session["AnswerSession"] = ""

    return render(request, "QandA/index.html", {
        "Text": request.session["Text"],
        "QuestionSession": request.session["QuestionSession"],
        "AnswerSession": request.session["AnswerSession"]
    })


def addText(request):
    if request.method == "POST":
        form = NewTextForm(request.POST)

        if form.is_valid():
            text = form.cleaned_data["text"]
            request.session["Text"] = text
            global mytext
            mytext = text
            return HttpResponseRedirect(reverse("QandA:index"))

        else:
            return render(request, "QandA/addText.html", {
                "form": form
            })

    return render(request, "QandA/addText.html", {
        "form": NewTextForm()
    })


def addQuestion(request):
    if request.method == "POST":
        form = NewQuestionFrom(request.POST)

        if form.is_valid():
            question = form.cleaned_data["question"]
            request.session["QuestionSession"] = question
            global myquestion
            myquestion = question
            request.session["AnswerSession"] = answer()
            return HttpResponseRedirect(reverse("QandA:index"))

        else:
            return render(request, "QandA/addQuestion.html", {
                "form": form
            })

    return render(request, "QandA/addQuestion.html", {
        "form": NewQuestionFrom()
    })


def answer():
    d = predictor.predict(
        passage=mytext,
        question=myquestion
    )
    res = d['best_span_str']

    return res

QandA/templates/QandA/addQuestion.html
{% extends "QandA/layout.html" %}

{% block body %}
    <h1> Add Question: </h1>
    <form action="{% url 'QandA:addQuestion' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'QandA:index' %}">View Answer</a>
{% endblock %}

QandA/templates/QandA/addText.html
{% extends "QandA/layout.html" %}

{% block body %}
    <h1> Add Text: </h1>
    <form action="{% url 'QandA:addText' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
    <a href="{% url 'QandA:index' %}">View Text</a>
{% endblock %}

QandA/templates/QandA/index.html
{% extends "QandA/layout.html" %}
{% block body %}
    <ul>
        <h3>Text</h3>
        <p>{{request.session.Text}}</p>
        <h3>Question</h3>
        <p>{{request.session.QuestionSession}}</p>
        <h3>Answer</h3>
        {{request.session.AnswerSession}}
    </ul>
    <a href="{% url 'QandA:addText' %}">Add a New Text</a>
    <a href="{% url 'QandA:addQuestion' %}">Ask a New Question</a>
{% endblock %}

QandA/templates/QandA/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tasks</title>
</head>
<body>
    {% block body %}
    {% endblock %}

</body>
</html>